### PR TITLE
Add issue templates for snscrape

### PR DESCRIPTION
**Pull request by TheTechRobo**
Test at https://github.com/TheTechRobo/snscrape/issues/new/choose

### CODE REVIEW

**Comment by TheTechRobo** [comment]
It might be a good idea to enable the Discussions tab, replacing the question label?

**Comment by JustAnotherArchivist** [comment]
I was going to say that I don't like issue templates, but it seems like they've improved quite a bit since i last looked into it. Thanks, will take a closer look soon.

I've been considering Discussions, but I haven't made a decision on it yet. I already dislike the platform lock-in of issues and PRs, but at least those are easy enough to migrate elsewhere if the need arises. Discussions are not.

**Comment by TheTechRobo** [comment]
Yep - these are the all new, nice and shiny, issue forms. They were added to GH a bit less than a year ago IIRC.

Out of curiosity, why didn't you like them before?

>   I already dislike the platform lock-in of issues and PRs, but at least those are easy enough to migrate elsewhere if the need arises. Discussions are not.

That's a good point. :thinking:

**Comment by JustAnotherArchivist** [comment]
The previous templates resulted in a lot of noise in the produced issue text because explanations, optional fields, etc. would have to be included in the template and many people wouldn't remove the irrelevant ones before submitting.

**Comment by TheTechRobo** [comment]
Here's an example issue for the bug report: https://github.com/TheTechRobo/snscrape/issues/1

**Comment by JustAnotherArchivist** [comment]
I forgor, but almost a year later, I'm finally back here. I don't like that it includes the optional, empty fields, but oh well. Let's see if this produces better issues. :-)

**Pull request merged**
