### PR TITLE
Add retries for flaky Twitter errors

### PR DESCRIPTION
**Pull request by novucs**
Errors can be often reproduced with the following user: jmrousseau

Even broken on Twitter itself, if you scroll down their page: https://twitter.com/jmrousseau

image

### CODE REVIEW

**Comment by novucs** [comment]
Caveat: This change broadly works for most users on Twitter, but there are still some nasty profiles out there that Twitter **really** struggles with.

Here's a sample of profiles that don't work, even with these changes:
https://twitter.com/GetVid_
https://twitter.com/MakeItACover
https://twitter.com/_screenshoter

They all appear to be reasonably popular reply bots, which I imagine is what's causing Twitter so much stress.

**Comment by JustAnotherArchivist** [comment]
Good point, and polishing this has been on my todo list for a release anyway. However, snscrape already has machinery for retrying requests, so this should be implemented using that instead.

**Comment by novucs** [comment]
> Good point, and polishing this has been on my todo list for a release anyway. However, snscrape already has machinery for retrying requests, so this should be implemented using that instead.

Thanks! I've refactored this to reuse existing retry logic now

**Comment by JustAnotherArchivist** [comment]
That would solve the immediate case of profile timelines, but Twitter can (and does) return errors everywhere, so it needs to be handled in `_check_api_response` instead. I've done the necessary changes locally, just testing it currently.

**Pull request closed without merging**
