### PR TITLE
twitter: Fix to KeyError & TweetTombstone

### PR DESCRIPTION
**Pull request by vladkens**
Hi. This PR contains a solution so that collecting tweets from the profile does not stop at these errors:
1) https://github.com/JustAnotherArchivist/snscrape/issues/603
2) fix for various KeyError errors
3) logger typo fix

Small script to test:
```python
import snscrape.modules.twitter as sntwitter
from collections import defaultdict


def main():
    uids = [
        366842064,  # tweet, KeyError: 'legacy'
        1154011190298910720,  # Unknown result type 'TweetTombstone'
    ]

    stats = defaultdict(int)
    for uid in uids:
        print(f"* {uid} ".ljust(60, "-"))

        rep = sntwitter.TwitterProfileScraper(uid).get_items()
        for i, x in enumerate(rep, 1):
            print(f"- {uid} {i} collected") if i % 500 == 0 else None
            stats[uid] += 1

    print(stats)


if __name__ == "__main__":
    main()
```

### CODE REVIEW

**Comment by JustAnotherArchivist** [comment]
The `KeyError`s need to be handled properly in the individual cases rather than just blindly catching them all. Emitting a warning is good, but those will undoubtedly be ignored by users, and I can't fix issues that aren't being reported...

The `TweetTombstone` also needs proper treatment in the `Tweet` object construction. It certainly shouldn't get silently ignored as your code does.

Thanks for catching the `_logger` typo! Do you happen to have an example which triggers that warning?

**Comment by vladkens** [comment]
@JustAnotherArchivist Hi. Yes, we can work together to make this solution better for these cases. I'm currently using the solution from PR to collect tweets from profiles, because otherwise the program crashes completely on data it can't process (I mean I can't scroll through the whole profile due to an error. For example 500 tweets were downloaded out of 3000 available, an error occurred and the program closed instead of just skipping this tweet, so I wrapped there in try / catch).

Examples:

1) **366842064 – tweet, KeyError: 'legacy'**
```
{"entryId": "tweet-1605972261457911808", "sortIndex": "1605972261457911808", "content": {"entryType": "TimelineTimelineItem", "__typename": "TimelineTimelineItem", "itemContent": {"itemType": "TimelineTweet", "__typename": "TimelineTweet", "tweet_results": {"result": {"__typename": "Tweet", "rest_id": "1605972261457911808", "core": {"user_results": {"result": {"__typename": "User", "id": "VXNlcjozNjY4NDIwNjQ=", "rest_id": "366842064", "affiliates_highlighted_label": {}, "has_nft_avatar": false, "is_blue_verified": false, "legacy": {"created_at": "Fri Sep 02 22:50:40 +0000 2011", "default_profile": true, "default_profile_image": false, "description": "Born and raised in NYC. Sassy Twitter Jew. Unapologetic Zionist with the audacity to exist. No patience for BS.", "entities": {"description": {"urls": []}}, "fast_followers_count": 0, "favourites_count": 180349, "followers_count": 5672, "friends_count": 2455, "has_custom_timelines": true, "is_translator": false, "listed_count": 35, "location": "", "media_count": 9869, "name": "kweansmom #JusticeForMalkiRoth", "normal_followers_count": 5672, "pinned_tweet_ids_str": ["1445159529604435975"], "possibly_sensitive": false, "profile_banner_extensions": {"mediaColor": {"r": {"ok": {"palette": [{"percentage": 61.83, "rgb": {"blue": 61, "green": 73, "red": 89}}, {"percentage": 23.6, "rgb": {"blue": 99, "green": 119, "red": 145}}, {"percentage": 7.23, "rgb": {"blue": 66, "green": 91, "red": 122}}, {"percentage": 3.11, "rgb": {"blue": 57, "green": 47, "red": 40}}, {"percentage": 1.38, "rgb": {"blue": 135, "green": 136, "red": 129}}]}}}}, "profile_banner_url": "https://pbs.twimg.com/profile_banners/366842064/1655167029", "profile_image_extensions": {"mediaColor": {"r": {"ok": {"palette": [{"percentage": 74.4, "rgb": {"blue": 105, "green": 116, "red": 130}}, {"percentage": 15.49, "rgb": {"blue": 46, "green": 97, "red": 143}}, {"percentage": 2.96, "rgb": {"blue": 85, "green": 165, "red": 210}}, {"percentage": 2.2, "rgb": {"blue": 18, "green": 51, "red": 93}}, {"percentage": 1.46, "rgb": {"blue": 167, "green": 180, "red": 196}}]}}}}, "profile_image_url_https": "https://pbs.twimg.com/profile_images/1536159014765088769/4h3Cqqwm_normal.jpg", "profile_interstitial_type": "", "protected": false, "screen_name": "kweansmom", "statuses_count": 126695, "translator_type": "none", "verified": false, "withheld_in_countries": []}, "super_follow_eligible": false, "super_followed_by": false, "super_following": false}}}, "unmention_data": {}, "edit_control": {"edit_tweet_ids": ["1605972261457911808"], "editable_until_msecs": "1671730399310", "is_edit_eligible": false, "edits_remaining": "5"}, "legacy": {"created_at": "Thu Dec 22 17:03:19 +0000 2022", "conversation_id_str": "1605972261457911808", "display_text_range": [0, 139], "entities": {"user_mentions": [{"id_str": "1511322362452529158", "name": "NJA", "screen_name": "NJA_UK", "indices": [3, 10]}, {"id_str": "471287735", "name": "Gary Lineker \ud83d\udc99\ud83d\udc9b", "screen_name": "GaryLineker", "indices": [40, 52]}], "urls": [], "hashtags": [], "symbols": []}, "favorite_count": 0, "favorited": false, "full_text": "RT @NJA_UK: We are appalled to see that @GaryLineker is mourning the death of a terrorist.\n\nAccording to Hamas, the terrorist group, Ahmed\u2026", "is_quote_status": true, "lang": "en", "quote_count": 0, "quoted_status_id_str": "1605883090634670080", "quoted_status_permalink": {"url": "https://t.co/KydUFmJ4Hy", "expanded": "https://twitter.com/GaryLineker/status/1605883090634670080", "display": "twitter.com/GaryLineker/st\u2026"}, "reply_count": 0, "retweet_count": 9, "retweeted": false, "user_id_str": "366842064", "id_str": "1605972261457911808", "retweeted_status_result": {"result": {"__typename": "Tweet", "rest_id": "1605942900730101760", "core": {"user_results": {"result": {"__typename": "User", "id": "VXNlcjoxNTExMzIyMzYyNDUyNTI5MTU4", "rest_id": "1511322362452529158", "affiliates_highlighted_label": {}, "has_nft_avatar": false, "is_blue_verified": true, "legacy": {"created_at": "Tue Apr 05 12:39:18 +0000 2022", "default_profile": true, "default_profile_image": false, "description": "The National Jewish Assembly (NJA) in UK focuses on Advocating and Defending Jewish Life, Supporting Israel & Fighting Antisemitism.   Please visit our website.", "entities": {"description": {"urls": []}, "url": {"urls": [{"display_url": "NJA.org.uk", "expanded_url": "http://www.NJA.org.uk", "url": "https://t.co/ZFTwRrwOCP", "indices": [0, 23]}]}}, "fast_followers_count": 0, "favourites_count": 271, "followers_count": 636, "friends_count": 173, "has_custom_timelines": false, "is_translator": false, "listed_count": 6, "location": "London, England", "media_count": 241, "name": "NJA", "normal_followers_count": 636, "pinned_tweet_ids_str": [], "possibly_sensitive": false, "profile_banner_extensions": {"mediaColor": {"r": {"ok": {"palette": [{"percentage": 34.25, "rgb": {"blue": 206, "green": 205, "red": 207}}, {"percentage": 21.82, "rgb": {"blue": 37, "green": 12, "red": 121}}, {"percentage": 17.37, "rgb": {"blue": 96, "green": 45, "red": 13}}, {"percentage": 5.25, "rgb": {"blue": 65, "green": 22, "red": 194}}, {"percentage": 3.56, "rgb": {"blue": 23, "green": 9, "red": 86}}]}}}}, "profile_banner_url": "https://pbs.twimg.com/profile_banners/1511322362452529158/1671965043", "profile_image_extensions": {"mediaColor": {"r": {"ok": {"palette": [{"percentage": 87.04, "rgb": {"blue": 255, "green": 255, "red": 255}}, {"percentage": 9.05, "rgb": {"blue": 240, "green": 188, "red": 108}}, {"percentage": 3.2, "rgb": {"blue": 161, "green": 78, "red": 42}}, {"percentage": 0.33, "rgb": {"blue": 158, "green": 107, "red": 81}}, {"percentage": 0.24, "rgb": {"blue": 224, "green": 147, "red": 87}}]}}}}, "profile_image_url_https": "https://pbs.twimg.com/profile_images/1572258794909978625/aGEPGd8g_normal.jpg", "profile_interstitial_type": "", "protected": false, "screen_name": "NJA_UK", "statuses_count": 759, "translator_type": "none", "url": "https://t.co/ZFTwRrwOCP", "verified": false, "withheld_in_countries": []}, "professional": {"rest_id": "1573281860930650115", "professional_type": "Business", "category": [{"id": 688, "name": "Non-Governmental & Nonprofit Organization ", "icon_name": "IconBriefcaseStroke"}]}, "super_follow_eligible": false, "super_followed_by": false, "super_following": false}}}, "unmention_data": {}, "edit_control": {"edit_tweet_ids": ["1605942900730101760"], "editable_until_msecs": "1671723399000", "is_edit_eligible": true, "edits_remaining": "5"}, "quoted_status_result": {"result": {"__typename": "Tweet", "rest_id": "1605883090634670080", "unmention_data": {}, "edit_control": {"edit_tweet_ids": ["1605883090634670080"], "editable_until_msecs": "1671709139000", "is_edit_eligible": true, "edits_remaining": "5"}}}, "legacy": {"created_at": "Thu Dec 22 15:06:39 +0000 2022", "conversation_id_str": "1605942900730101760", "display_text_range": [0, 262], "entities": {"user_mentions": [{"id_str": "471287735", "name": "Gary Lineker \ud83d\udc99\ud83d\udc9b", "screen_name": "GaryLineker", "indices": [28, 40]}], "urls": [], "hashtags": [], "symbols": []}, "favorite_count": 35, "favorited": false, "full_text": "We are appalled to see that @GaryLineker is mourning the death of a terrorist.\n\nAccording to Hamas, the terrorist group, Ahmed Daraghmeh was \u2018its martyr\u2019, and was killed in an armed conflict.\n\nWhat\u2019s awful is how you decided it was acceptable to post this tweet.", "is_quote_status": true, "lang": "en", "quote_count": 2, "quoted_status_id_str": "1605883090634670080", "quoted_status_permalink": {"url": "https://t.co/KydUFmJ4Hy", "expanded": "https://twitter.com/GaryLineker/status/1605883090634670080", "display": "twitter.com/GaryLineker/st\u2026"}, "reply_count": 6, "retweet_count": 9, "retweeted": false, "user_id_str": "1511322362452529158", "id_str": "1605942900730101760"}}}}, "views": {"state": "Enabled"}}}, "tweetDisplayType": "Tweet", "ruxContext": "HHwWgICg-eejusksAAAA", "innerTombstoneInfo": {"text": "", "richText": {"rtl": false, "text": "You\u2019re unable to view this Tweet because this account owner limits who can view their Tweets. Learn more", "entities": [{"fromIndex": 94, "toIndex": 104, "ref": {"type": "TimelineUrl", "url": "https://help.twitter.com/rules-and-policies/notices-on-twitter", "urlType": "ExternalUrl"}}]}}}}}
```

2) **1154011190298910720 – Unknown result type 'TweetTombstone'**
```
{"entryId": "tweet-1434275838275563520", "sortIndex": "1434275838275563520", "content": {"entryType": "TimelineTimelineItem", "__typename": "TimelineTimelineItem", "itemContent": {"itemType": "TimelineTweet", "__typename": "TimelineTweet", "tweet_results": {"result": {"__typename": "TweetTombstone", "tombstone": {"__typename": "TextTombstone", "text": {"rtl": false, "text": "Age-restricted adult content. This content might not be appropriate for people under 18 years old. To view this media, you\u2019ll need to log in to Twitter. Learn more", "entities": [{"fromIndex": 134, "toIndex": 140, "ref": {"type": "TimelineUrl", "url": "https://twitter.com", "urlType": "ExternalUrl"}}, {"fromIndex": 153, "toIndex": 163, "ref": {"type": "TimelineUrl", "url": "https://help.twitter.com/rules-and-policies/notices-on-twitter", "urlType": "ExternalUrl"}}]}}}}, "tweetDisplayType": "Tweet", "ruxContext": "HHwWgsC-0a2a-eMnAAAA"}, "reactiveTriggers": {"onLinger": {"execution": {"type": "TimelineImmediateTimelineReaction", "key": "-580653399"}, "maxExecutionCount": 1}}}}
```
TweetTombstone data is useless in my opinion, so I decided to just skip it

**Comment by vladkens** [comment]
> Both of those are actually examples of tombstones. And they might be useless to you, but in general, it may be important to record that there is content that isn't accessible (and why).

I can suggest adding a new data type to snscrape that would indicate content that could not be retrieved. That way those working with the api can receive such messages and deal with them somehow. In general I agree that it would be useful for me too to get such unavailable tweets for statistics. For example: `snscrape.modules.twitter.Unavailable`

We can also add a startup flag / parameter in the class to regulate this behaviour - i.e. show or not show these messages in the feed by default. Ideally this should not be shown by default to maintain backwards compatibility.

If you agree with these thoughts I can update the PR.

> I was more curious about examples that trigger the logger typo lines. Or did you just happen to spot that while working on the code?

I noticed these typos when I was working on the code.

**Comment by JustAnotherArchivist** [comment]
Yes, a new `Item` dataclass in the Twitter module for this would be the way to go. I'd call it `Tombstone`, and it should have at least an attribute `text: str` containing the explanation shown on the web interface. I think tombstones can also contain links though, which gets a bit more complicated. Maybe the existing link handling code can work for that, but I'm not sure whether Twitter returns the data in the same way. If it does, it'd probably need to be `rawText` and `renderedText`, similar to tweet contents or profile descriptions. I do know that Twitter has several ways of returning tombstones; I believe it works differently for scraping individual tweets, profiles, and quoted/retweeted tweets. These would all need to be supported (and tested with examples).

I don't want a flag for this though; they should always be returned (or, more accurately, yielded), and if the user doesn't want the tombstones, they can filter them out themselves.

**Comment by JustAnotherArchivist** [comment]
@vladkens Are you still working on or interested in implementing the tombstone handling? If not, I'll look into it this weekend.

**Comment by JustAnotherArchivist** [comment]
Obsoleted by 6a6b02cb and 3d6cd63a.
As mentioned before, `KeyError`s should be reported individually as bugs so they can be fixed properly.

**Pull request closed without merging**
