### PR TITLE
Added proxy option to Scraper base

### PR DESCRIPTION
**Pull request by own3dh2so4**
With this change, you can add a proxy to the scraper.

### CODE REVIEW

**Comment by own3dh2so4** [comment]
In my case, I am using this project as a library, not as CLI.

I have two proxy providers, one "cheaper" and another "more expensive". The cheaper proxy works fine with Twitter, but for Facebook and Google I need use the expensive proxy.

I chose the proxy programmatically, based on the website that I will crawl. I don't want to change the environment variables of my service programmatically, I prefer to pass the proxy to de Crawler builder.

**Comment by own3dh2so4** [comment]
@JustAnotherArchivist can you release a new version with this change?

thx!

**Comment by TheTechRobo** [comment]
you can use the development version before he does

**Comment by JustAnotherArchivist** [comment]
Probably in the next few days. If you need this immediately, yeah, please use the dev version until then.

**Comment by indiecatta** [comment]
for the same reason as OP (different social networks may need different proxies) i think it would be appropriate to add parameters that allow you to specify the proxy to be used via CLI.
What do you think? @JustAnotherArchivist

**Comment by JustAnotherArchivist** [comment]
@indiecatta You cannot run multiple scrapes in one process with the CLI, so that use case does not apply. You can just set `http_proxy` and `HTTPS_PROXY` accordingly based on the target network before you execute the CLI.

**Pull request merged**
