### PR TITLE
Add more fields to the instagram scraper

### PR DESCRIPTION
**Pull request by JackDallas**
I meant to do this ages ago, some more fields you can access from an instagram post, I ran this against several 100 thousand posts from the hashtag page (https://github.com/JackDallas/snscrape/blob/add-insta-hashtag-example/examples/insta_hashtag_farmer.py) and it was all good :ok_hand:

### CODE REVIEW

**Comment by JustAnotherArchivist** [comment]
Sorry for only getting back to this now.

It appears that Instagram changed something in the last couple months: as of right now, `edge_liked_by` does not exist in the GraphQL response, but it is in the initial page, so as soon as snscrape fakes the scrolling, it crashes. There's `edge_media_preview_likes`, which is present in both the page and GraphQL, but I'm not sure if there's any difference between the two.

The other fields are working fine as far as I can see.

**Comment by JackDallas** [comment]
Okay, updated and checked against 1000 posts from the instagram account, ty @JustAnotherArchivist

**Comment by JackDallas** [comment]
Do you want the commits squashed ??

**Comment by JustAnotherArchivist** [comment]
Sweet, thank you. I just verified that the Instagram profile page JS does indeed use that field for the like count shown on a post mouseover, as expected.

**Pull request merged**
